import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers";
import { NavBar } from "./components/navbar/Navbar";
import { ApiCallProvider } from "@/utils/context/api_call_context";

const rubik = Rubik({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "worknify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body className={rubik.className}>
        <Providers>
          <ApiCallProvider>
            <NavBar />
            {children}
          </ApiCallProvider>
        </Providers>
      </body>
    </html>
  );
}
