import type { Metadata } from "next";
import {Rubik} from "next/font/google";
import "../globals.css";
import { Navbar } from "./components/navbar/Navbar";

const rubik = Rubik({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "worknify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
