import "../globals.css";
import { Rubik } from "next/font/google";
import { Metadata } from "next";
import { UserInfoProvider } from "@/global-components/UserInfoProvider";
const rubik = Rubik({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <UserInfoProvider>{children}</UserInfoProvider>
      </body>
    </html>
  );
}
